apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-sa
  namespace: fraud
  annotations:
    # Workload Identity binding to GCP service account
    iam.gke.io/gcp-service-account: flink-cluster@hsbc-484505.iam.gserviceaccount.com
