apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-sa
  namespace: fraud
  annotations:
    # Workload Identity binding to GCP service account
    iam.gke.io/gcp-service-account: flink-cluster@hsbc-484505.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink-role
  namespace: fraud
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-role-binding
  namespace: fraud
subjects:
  - kind: ServiceAccount
    name: flink-sa
    namespace: fraud
roleRef:
  kind: Role
  name: flink-role
  apiGroup: rbac.authorization.k8s.io
